import Drag from './collection/drag.svg'
import Stop from './collection/stop.svg'
import Auto from './collection/auto.svg'
import Swap from './collection/swap.svg'
import Time from './collection/time.svg'
import Edit from './collection/edit.svg'
import Play from './collection/play.svg'
import Plus from './collection/plus.svg'
import Info from './collection/info.svg'
import Games from './collection/games.svg'
import InfoSmall from './collection/info-small.svg'
import InfoOutline from './collection/info-outline.svg'
import Apps from './collection/apps.svg'
import AppsAll from './collection/apps-all.svg'
import Color from './collection/color.svg'
import Sunny from './collection/sunny.svg'
import Place from './collection/place.svg'
import Focus from './collection/focus.svg'
import Pause from './collection/pause.svg'
import Close from './collection/close.svg'
import Photo from './collection/photo.svg'
import Video from './collection/video.svg'
import Broom from './collection/broom.svg'
import Check from './collection/check.svg'
import Logout from './collection/logout.svg'
import Listen from './collection/listen.svg'
import Rocket from './collection/rocket.svg'
import Quotes from './collection/quotes.svg'
import Delete from './collection/delete.svg'
import Camera from './collection/camera.svg'
import Upload from './collection/upload.svg'
import Search from './collection/search.svg'
import SearchOut from './collection/search-out.svg'
import SearchFocus from './collection/search-focus.svg'
import Person from './collection/person.svg'
import NewTab from './collection/new-tab.svg'
import Payment from './collection/payment.svg'
import Dislike from './collection/dislike.svg'
import NoPlace from './collection/no-place.svg'
import PlusBig from './collection/plus-big.svg'
import Password from './collection/password.svg'
import Location from './collection/location.svg'
import CheckBig from './collection/check-big.svg'
import CloseBig from './collection/close-big.svg'
import CloseSmall from './collection/close-small.svg'
import DinoGame from './collection/dino-game.svg'
import Extension from './collection/extension.svg'
import LifeTimer from './collection/life-timer.svg'
import NoWeather from './collection/no-weather.svg'
import Background from './collection/background.svg'
import NoLocation from './collection/no-location.svg'
import ClearNight from './collection/clear-night.svg'
import CheckSmall from './collection/check-small.svg'
import CleanScreen from './collection/clean-screen.svg'
import Affirmations from './collection/affirmations.svg'
import NoConnection from './collection/no-connection.svg'
import AppAhead from './collection/app-ahead.svg'
import Settings from './collection/settings.svg'
import SettingsGear from './collection/settings-gear.svg'
import WeatherLoading from './collection/weather-loading.svg'
import SettingsSwitches from './collection/settings-switches.svg'
import SpinnerThin from './collection/spinner-thin.svg'
import Spinner from './collection/spinner.svg'
import Debug from './collection/debug.svg'

import Sms from './collection/sms.svg'
import Map from './collection/map.svg'
import Pin from './collection/pin.svg'
import PinOutline from './collection/pin-outline.svg'
import News from './collection/news.svg'
import Copy from './collection/copy.svg'
import Refresh from './collection/refresh.svg'
import History from './collection/history.svg'
import HistoryOutline from './collection/history-outline.svg'
import Cloud from './collection/cloud.svg'
import CloudOn from './collection/cloud-on.svg'
import Download from './collection/download.svg'
import CloudOff from './collection/cloud-off.svg'
import CloudSmol from './collection/cloud-smol.svg'
import Bookmarks from './collection/bookmarks.svg'
import Launchpad from './collection/launchpad.svg'
import OpenInNew from './collection/open-in-new.svg'
import SubtaskAdd from './collection/subtask-add.svg'

import New from './collection/new.svg'
import More from './collection/more.svg'
import Share from './collection/share.svg'
import Coffee from './collection/coffee.svg'
import Privacy from './collection/privacy.svg'
import Contacts from './collection/contacts.svg'
import Keyboard from './collection/keyboard.svg'
import KeyboardSmol from './collection/keyboard-smol.svg'
import PhoneLink from './collection/phone-link.svg'

import Translate from './collection/translate.svg'
import Calendar from './collection/calendar.svg'
import Notes from './collection/notes.svg'
import Tasks from './collection/tasks.svg'
import Device from './collection/device.svg'

import Facebook from './collection/facebook.svg'
import Telegram from './collection/telegram.svg'
import Twitter from './collection/twitter.svg'
import Discord from './collection/discord.svg'
import Mail from './collection/mail.svg'

import Icon8x8 from './collection/8x8.svg'
import Zoom from './collection/zoom.svg'
import Jitsi from './collection/jitsi.svg'
import Chime from './collection/chime.svg'
import Skype from './collection/skype.svg'
import Slack from './collection/slack.svg'
import Teams from './collection/teams.svg'
import Webex from './collection/webex.svg'
import Google from './collection/google.svg'
import Around from './collection/around.svg'
import Facetime from './collection/facetime.svg'
import BlueJeans from './collection/bluejeans.svg'
import GotoMeeting from './collection/gotomeeting.svg'
import VideoCamera from './collection/video-camera.svg'

import ArrowBack from './collection/arrow-back.svg'
import ArrowForward from './collection/arrow-forward.svg'

import Warning from './collection/warning.svg'
import Holiday from './collection/holiday.svg'
import Birthday from './collection/birthday.svg'
import SidebarAttach from './collection/sidebar-attach.svg'
import SidebarDetach from './collection/sidebar-detach.svg'

import Mouse from './collection/mouse.svg'
import Folder from './collection/folder.svg'
import FolderAdd from './collection/folder-add.svg'
import FolderOpen from './collection/folder-open.svg'
import FolderOutline from './collection/folder-outline.svg'
import FolderOpenOutline from './collection/folder-open-outline.svg'
import Advert from './collection/advert.svg'
import Help from './collection/help.svg'
import Window from './collection/window.svg'
import Calculator from './collection/calculator.svg'
import Gpt from './collection/gpt.svg'
import Home from './collection/home.svg'
import Todoist from './collection/todoist.svg'
import TickTick from './collection/tick-tick.svg'
import MicrosoftTodo from './collection/microsoft-todo.svg'
import GoogleTasks from './collection/google-tasks.svg'
import GoogleKeep from './collection/google-keep.svg'

import Love from './collection/love.svg'
import AdsOff from './collection/ads-off.svg'
import Priority from './collection/priority.svg'
import AutoOpen from './collection/auto-open.svg'
import AccountSmall from './collection/account-small.svg'
import AccountSmallPlus from './collection/account-small-plus.svg'

import GoogleDrive from './collection/google-drive.svg'
import SharedDrive from './collection/shared-drive.svg'
import SharedWithMe from './collection/shared-with-me.svg'
import StarredDrive from './collection/starred-drive.svg'
import MyDrive from './collection/my-drive.svg'
import Star from './collection/star.svg'
import StarOutline from './collection/star-outline.svg'

export default {
  Drag, Play, Pause, Search, SearchOut, SearchFocus, Location, NoLocation, Place, NoPlace, Time,
  Sunny, ClearNight, Photo, Video, Delete, Camera, Settings, SettingsGear, Upload, Dislike,
  SettingsSwitches, Background, CleanScreen, NoConnection, NoWeather, Quotes, Affirmations,
  LifeTimer, Focus, WeatherLoading, Edit, Rocket, Plus, PlusBig, Broom, Check, CheckBig,
  CheckSmall, CloseSmall, Close, CloseBig, Pin, PinOutline, History, HistoryOutline, Download, Copy,
  Cloud, CloudOn, CloudOff, CloudSmol, Bookmarks, Refresh, NewTab, Password, Payment,
  Extension, Info, InfoOutline,
  InfoSmall, DinoGame, Apps, AppsAll, Map, News, New, More, Share, Coffee, Privacy, Contacts,
  Keyboard, KeyboardSmol, Translate, Calendar, Notes, Tasks, Facebook, Twitter, Discord,
  Telegram, Mail, Auto, Listen, Swap, Stop, OpenInNew, Spinner, SpinnerThin, Icon8x8, Zoom,
  Chime, Skype, Slack, Jitsi, Teams, Webex, Google, Around, Facetime, BlueJeans, GotoMeeting,
  VideoCamera, ArrowBack, ArrowForward, Warning, Holiday, Birthday, SubtaskAdd, Sms, Color,
  Person, Device, PhoneLink, Logout, Debug, AppAhead, SidebarAttach, SidebarDetach,
  Folder, FolderAdd, FolderOpen, FolderOutline, FolderOpenOutline, Launchpad, Mouse, Advert, Games,
  Help, Window, Calculator, Gpt, Todoist, TickTick, MicrosoftTodo, Home, GoogleTasks, GoogleKeep,
  AdsOff, AutoOpen, Love, Priority, AccountSmall, AccountSmallPlus,
  GoogleDrive, SharedDrive, SharedWithMe, StarredDrive, MyDrive, Star, StarOutline
}
